### PR TITLE
[VFS] Fixed allow_game_relative_writes to write invalid cached entries

### LINKED ISSUE #123: allow_game_relative_writes won't overwrite an existing file even if removed before write.
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

I am working on a mod for a game that will be saving custom information on disk. On console, I can generate a new file as long as I delete the file beforehand. In xenia, even if I delete the file first, a new file will not be generated. This behavior also extends if the file exists on disk when I boot the game, (assuming mounted to game: at runtime) I have to close xenia and relaunch the game to generate a new file from within the game.

https://user-images.githubusercontent.com/55568980/216476782-96b95705-5b1e-4efa-817a-49eb99079b74.mp4

### Describe what should happen

since I deleted the file, on the disk, the game should be able to write to that file again without the game being relaunched, thus remounting game:

### If applicable, provide a callstack here, especially for crashes

_No response_

### If applicable, upload a logfile and link it here

_No response_

### PR DESCRIPTION
**Pull request by AdrianCassar**
This PR fixes https://github.com/xenia-canary/xenia-canary/issues/123 a bug where files would not write to the host if they were deleted from the host filesystem during runtime.

### CODE REVIEW

**Comment by jnackmclain** [comment]
I can confirm this PR resolves the issue

File: src/xenia/vfs/virtual_file_system.cc [hunk 1]
```diff
@@ -221,6 +222,26 @@ X_STATUS VirtualFileSystem::OpenFile(Entry* root_entry,
     if (entry->attributes() & kFileAttributeDirectory && is_non_directory) {
       return X_STATUS_FILE_IS_A_DIRECTORY;
     }
+
+    // If the entry does not exist on the host then remove the cached entry
+    // forcefully by "overwriting" the non-existent file
+    if (parent_entry) {
+      xe::vfs::HostPathEntry* host_Path =
```
Comment (Gliniak) [inline src/xenia/vfs/virtual_file_system.cc]: const + host_path instead of host_Path

Btw. What would happen if game tries to do something strange during savefile loading? It might expect different result?
